#!/bin/bash
#

if [[ "$EUID" -ne 0 ]]; then
    echo -e "\n[*] Run as root!\n"
    exit 1
fi

LBA=$(smartctl -a /dev/sda | awk '/Total_LBAs_Written/ {print $NF}')

# Convert LBA → GiB
written_gib=$(echo "scale=2; (${LBA} * 512) / (1024^3)" | bc -l)

echo "${written_gib} GiB Written / 307200 GiB (300 TiB)"

