#!/bin/bash

### { 

	# configuration part of this script

	url="https://ubuntu.com/download/desktop"
	ver="19.10"
	dwnUrl="https://ubuntu.osuosl.org/releases/$ver/ubuntu-$ver-desktop-amd64.iso"
	chkFreq=90
	mode=$1

### } 

id=2004

case $mode in
	"--desktop"|"--mobile-phone")
	   	trap 'echo -e " \e[1;31mSignal Recieved SIG$( kill -l $(($? - 128)) ) \e[0m- to exit give the bellow command\n\e[33mkill -SIGKILL $$\e[0m"' SIGHUP  SIGINT SIGTERM SIGUSR1 SIGUSR2 SIGPIPE SIGQUIT EXIT SIGABRT 
		;;
esac

main(){

case $mode in
	"--desktop")
		desktop
		;;
	"--mobile-phone")
		termux-wake-lock && \
		mobile-phone || \
		echo -e "\e[1;31m wake-lock could not start \e[0m"
		;;
	"-h"|"--help")
		usage
		;;
	*)
		echo -e "\n\e[1;31m unknown option: $mode ?\n\e[0m"
		usage
		;;
esac
return 0
}


mobile-phone(){

	termux-notification-remove $id
	
	while :
	do
	
		count=`curl -s $url | grep -ic $ver`
		curl -Ifs $dwnUrl > /dev/null 2>&1 && exist=0 || exist=1
	
		if [[ "$count" != "0" || "$exist" == "0" ]]; then
	
			#echo "After matched count = $count"
			echo "Ubuntu $ver LTS Launched ..!!" 
	
	
			termux-notification -i $id \
				-c "Ubuntu $ver LTS Launched ..!!" \
			  	-t "Ubuntu $ver" \
				--led-color ffffff \
				--button1 "Download" \
				--button1-action "termux-download $dwnUrl" \
				--on-delete "termux-clipboard-set $dwnUrl" \
				--action "termux-download $dwnUrl" \
				--ongoing \
				--priority "high" 
	
			termux-volume alarm 100

			termux-clipboard-set "$dwnUrl" && \
			echo -e "Download Url copied to clipboard\n" && \
			termux-toast "Download Url Copied to Clipboard"
	
			sleep 1 
	
			while :
			do
				
				termux-toast -b "green" \
				   	-g "middle" \
					"Ubuntu $ver LTS Launched ..!!" 
	
				termux-vibrate -d 4000 -f
	
	
				termux-tts-speak -p 2 -s ALARM \
								 "ALERT...!! UBUNTU $ver RELEASED...!!" 
	
				sleep 2
	
			done
	
		fi
	
		sleep $chkFreq   
	
	done
	
}





desktop(){

	while :
	do
	
	    count=`curl -s $url | grep -ic $ver`
		curl -Ifs $dwnUrl > /dev/null 2>&1 && exist=0 || exist=1
	
	    if [[ "$count" != "0" || "$exist" == "0" ]]; then

			#echo "After matched count = $count"
	    	echo -e "\nUbuntu $ver LTS Launched ..!!" 
			echo $dwnUrl | xclip -selection clipboard -i && \
			echo -e "Download Url Copied to Clipboard\n"

			while :
			do

				recieve=$(dunstify -a "Ubuntu $ver" \
					-u "critical" \
					-r $id \
					--action="Download,Download" \
					--action="cancel,Cancel" \
					"Ubuntu $ver Launched...!!" \
					"\n<b>Yupii...Ubuntu $ver is Launched..!!</b>")
	
				case $recieve in
					"Download")
						xdg-open $dwnUrl
						;;
					"cancel")
						dunstify -C $id
	
				esac

				sleep 2

			done
	
		fi

		sleep $chkFreq

	done
	
	
}

usage(){

	echo -e "\n\033[1;33m Description:\033[0m\n\n\t This script check whether Ubuntu 20.04 is released or not,\n if released show you a notification with download button, if you\n select \"Download\", script redirect you to your default browser and\n automatically start download Ubuntu 20.04"
	echo -e "\n\e[1;33m Usage :\e[0m"

	echo -e "\n\e[1m -h,--help \e[0m\n\n\t Show this help \n\
		\n\e[1m --desktop \e[0m\n\n\t use this script for desktop or pc \n\
		\n\e[1m --mobile-phone \e[0m\n\n\t use this script in mobile with termux\n"

}

# { ******************** body of the scripts *******************


	main $mode


# } ****************** End of the Script *********************
