[Audio]
Volume=100

[General]
ColorScheme=Kvantum
GuiStyle=kvantum-dark
LastPlayedFile=file:///mnt/shared-storage/Java/tutorials/coder_army/lld/Shubh Patel/13 - Design Parking Lot ｜ Low Level Design (LLD), UML, Concurrency & Code Explained.mkv
ShowTaskbarProgress=true

[Playback]
HWDecoding=no
OpenLastPlayedFile=true
RestoreFilePosition=true

[Playlist]
RememberState=true
