[Shortcuts]
seekBackwardBigAction=Left
seekBackwardSmallAction=Ctrl+Left
seekForwardBigAction=Right
seekForwardMediumAction=Shift+Right
seekForwardSmallAction=Ctrl+Right
seekNextSubtitleAction=Alt+Right
seekPreviousSubtitleAction=Alt+Left
subtitleCycleUpAction=Shift+V
videoPanYDownAction=Ctrl+Alt+Down
volumeDownAction=Down
volumeUpAction=Up
