
# ==============================================================================
# XDG Base Directories Specification
# ==============================================================================
XDG_CONFIG_HOME=${HOME}/.config
XDG_DATA_HOME=${HOME}/.local/share
XDG_CACHE_HOME=${HOME}/.cache
XDG_STATE_HOME=${HOME}/.local/state
XDG_DATA_DIRS=/usr/local/share:/usr/share
XDG_CONFIG_DIRS=/etc/xdg

# ==============================================================================
# Desktop Session Identification
# ==============================================================================
#XDG_CURRENT_DESKTOP=sway
#XDG_SESSION_DESKTOP=sway
XDG_SESSION_TYPE=wayland

# ==============================================================================
# Toolkit & Application Integration (Wayland Native)
# ==============================================================================
# GTK
GDK_BACKEND=wayland,x11

# Qt
QT_QPA_PLATFORM="wayland;xcb"
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# Firefox & Thunderbird
MOZ_ENABLE_WAYLAND=1

# Electron / Chromium Apps
ELECTRON_OZONE_PLATFORM_HINT=auto

# System-wide dark mode flag for portals and GTK applications
GTK_THEME=Vimix-dark-compact-amethyst
