# Shell variables
# Generated by 'wal'
wallpaper="/home/sourav/.local/share/wallpapers/2_DisertArt.jpg"

# Special
background='#351f19'
foreground='#ccc7c5'
cursor='#ccc7c5'

# Colors
color0='#351f19'
color1='#709793'
color2='#7DC1BD'
color3='#98A79F'
color4='#E0AA99'
color5='#A0C8B8'
color6='#ECDCA9'
color7='#ccc7c5'
color8='#7d6b66'
color9='#709793'
color10='#7DC1BD'
color11='#98A79F'
color12='#E0AA99'
color13='#A0C8B8'
color14='#ECDCA9'
color15='#ccc7c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
