--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sourav/.local/share/wallpapers/2_DisertArt.jpg"

-- Special
background="#351f19"
foreground="#ccc7c5"
cursor="#ccc7c5"

-- Colors
color0="#351f19"
color1="#709793"
color2="#7DC1BD"
color3="#98A79F"
color4="#E0AA99"
color5="#A0C8B8"
color6="#ECDCA9"
color7="#ccc7c5"
color8="#7d6b66"
color9="#709793"
color10="#7DC1BD"
color11="#98A79F"
color12="#E0AA99"
color13="#A0C8B8"
color14="#ECDCA9"
color15="#ccc7c5"
