#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

submenu --class shutdown "Reboot / Poweroff..." {

	menuentry --class shutdown "Poweroff" {
		echo "Going to be poweroff..."
		halt
	}
	
	menuentry --class restart "Reboot" {
		echo "Going to be reboot..."
		reboot
	}

}
