#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'Windows Boot Manager (on /dev/sda1)' --class windows --class os $menuentry_id_option 'osprober-efi-A526-9474' {
	insmod part_gpt
	insmod fat
	set root='hd0,gpt1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt1 --hint-efi=hd0,gpt1 --hint-baremetal=ahci0,gpt1  A526-9474
	else
	  search --no-floppy --fs-uuid --set=root A526-9474
	fi
	chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}

menuentry 'Arch Linux HDD (rolling) (on /dev/sdb7)' --class arch --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-simple-24811c53-8920-4c58-9e53-c8e59f9f9f9d' {
	insmod part_gpt
	insmod fat
	insmod chain
	insmod search_fs_uuid
	search --fs-uuid --no-floppy --set=root 1421-3AA5
	chainloader ($root)/EFI/Arch-Linux/grubx64.efi
}

submenu --class shutdown "Reboot / Poweroff..." {

	menuentry --class shutdown "Poweroff" {
		echo "Going to be poweroff..."
		halt
	}
	
	menuentry --class restart "Reboot" {
		echo "Going to be reboot..."
		reboot
	}

}
#menuentry "Arch-Linux-ssd" {
#	insmod part_gpt
#	insmod fat
#	insmod chain
#	insmod search_fs_uuid
#	search --fs-uuid --no-floppy --set=root 9379-C7AB
#	chainloader ($root)/EFI/Arch-Linux-ssd/grubx64.efi
#}
#menuentry "Arch-Linux-ssd chainLoader1" {
#	insmod part_gpt
#	insmod fat
#	insmod chain
#	chainloader (hd0,7)+1
#}
#menuentry "Arch-Linux-ssd configLoading1" {
#	insmod part_gpt
#	insmod fat
#	insmod chain
#	chainloader (hd0,7)+1
#}
#menuentry "Arch-Linux-ssd configLoading2" {
#	set root='hd0,gpt7'
#	configfile ($root)/EFI/Arch-Linux-ssd/grubx64.efi
#}
#menuentry "Arch-Linux-ssd configLoading3" {
#configfile (hd0,gpt7)/EFI/Arch-Linux-ssd/grubx64.efi
#}
